# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_0',
                'doc_host': 'https://LiFengJu.github.io',
                'git_url': 'https://github.com/LiFengJu/nbdev_0',
                'lib_path': 'nbdev_0'},
  'syms': {'nbdev_0.core': {'nbdev_0.core.foo': ('core.html#foo', 'nbdev_0/core.py')}}}
